/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BDSimulatorCLi.app;

class MessageUtils {
    public static String getMessage() {
        return "Helloddd      World!";
    }
}
